sudo: required
dist: trusty
language: cpp

# disable the default submodule logic
git:
  submodules: false

before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository --yes ppa:beineri/opt-qt542-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt54serialport qt54tools

# before_script:
# enable graphical window for gui testing
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start

script:
  - source /opt/qt54/bin/qt54-env.sh && mkdir -p build && cd build && /opt/qt54/bin/qmake  "CONFIG+=release test" ../sprelay.pro -r
  - make
  - cd ../bin && ./sprelayunittests
  - cd .. && python third_party/cpplint-1.3.0/cpplint.py --recursive src/sprelay tests
